sudo: required

services:
  - docker

before_install:
  - docker build  -t  anchalke/frontend:1.0  -f  ./frontend/Dockerfile.dev ./frontend
  
script:
  - docker run  anchalke/frontend:1.0 npm run test  --  --coverage